<script setup lang="ts">
import { ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useDocumentStore } from '@/stores/document'
import { useReferencesStore } from '@/stores/references'
import { useToast } from '@/composables/useToast'
import { CHAPTERS } from '@/constants/chapters'
import SectionEditor from './SectionEditor.vue'
import BodyEditor from './BodyEditor.vue'
import ReferenceEditor from './ReferenceEditor.vue'
import TOCPreview from './TOCPreview.vue'
import DropZone from './DropZone.vue'
import ConfirmDialog from '@/components/shared/ConfirmDialog.vue'

const docStore = useDocumentStore()
const refStore = useReferencesStore()
const toast = useToast()
const { totalCharCount, paragraphCount } = storeToRefs(docStore)
const { count: refCount } = storeToRefs(refStore)

const expanded = ref(new Set<string>(['body']))
const showClearConfirm = ref(false)

function toggleChapter(id: string) {
  if (expanded.value.has(id)) {
    expanded.value.delete(id)
  } else {
    expanded.value.add(id)
  }
  expanded.value = new Set(expanded.value)
}

function sectionCharCount(key: string): number {
  if (key === 'references') return refStore.count
  if (key === 'toc') return 0
  if (key in docStore.sections) {
    return docStore.sections[key as keyof typeof docStore.sections].length
  }
  return 0
}

function confirmClear() {
  docStore.clearAll()
  showClearConfirm.value = false
  toast.show('已清空全部章节内容', 'info')
}
</script>

<template>
  <div class="editor-panel">
    <div class="editor-chapters">
      <div
        v-for="chapter in CHAPTERS"
        :key="chapter.id"
        class="chapter-block"
        :class="{ expanded: expanded.has(chapter.id) }"
      >
        <button class="chapter-header" @click="toggleChapter(chapter.id)">
          <span class="chapter-expand-icon">{{ expanded.has(chapter.id) ? '▾' : '▸' }}</span>
          <span class="chapter-title">{{ chapter.title }}</span>
          <span class="chapter-subtitle">{{ chapter.subtitle }}</span>
          <span v-if="!chapter.isAutoGenerated" class="chapter-char-count">
            {{ sectionCharCount(chapter.id) }}
          </span>
          <span v-if="chapter.isAutoGenerated" class="chapter-auto-tag">自动</span>
        </button>

        <div v-if="expanded.has(chapter.id)" class="chapter-body">
          <!-- 中文摘要 -->
          <SectionEditor
            v-if="chapter.id === 'abstractZh'"
            section-key="abstractZh"
            placeholder="中文摘要
摘要
在此输入中文摘要正文（200-300 字）...
关键词：关键词1；关键词2；关键词3"
            :min-rows="8"
          />

          <!-- 英文摘要 -->
          <SectionEditor
            v-else-if="chapter.id === 'abstractEn'"
            section-key="abstractEn"
            placeholder="Abstract
Abstract
Enter English abstract content here...
Keywords: keyword1; keyword2; keyword3"
            :min-rows="8"
          />

          <!-- 目录 -->
          <TOCPreview v-else-if="chapter.id === 'toc'" />

          <!-- 正文 -->
          <BodyEditor v-else-if="chapter.id === 'body'" />

          <!-- 参考文献 -->
          <ReferenceEditor v-else-if="chapter.id === 'references'" />

          <!-- 致谢 -->
          <SectionEditor
            v-else-if="chapter.id === 'acknowledgement'"
            section-key="acknowledgement"
            placeholder="致谢
在此输入致谢内容（限 1 页内）..."
            :min-rows="5"
          />

          <!-- 附录 -->
          <SectionEditor
            v-else-if="chapter.id === 'appendix'"
            section-key="appendix"
            placeholder="附录
在此输入附录内容（可选，公式推导、原始数据、代码等）..."
            :min-rows="5"
          />
        </div>
      </div>
    </div>

    <footer class="editor-status">
      <span class="status-stats">
        共 {{ totalCharCount }} 字 · {{ paragraphCount }} 段 · 7 章节
      </span>
      <button
        v-if="docStore.hasContent || refCount > 0"
        class="status-clear"
        @click="showClearConfirm = true"
      >
        清空
      </button>
    </footer>

    <DropZone />

    <ConfirmDialog
      :show="showClearConfirm"
      title="清空全部内容"
      message="将清空所有章节的编辑内容（中文摘要、英文摘要、正文、参考文献、致谢、附录）及解析结果，此操作不可撤销。"
      confirm-text="确认清空"
      cancel-text="取消"
      @confirm="confirmClear"
      @cancel="showClearConfirm = false"
    />
  </div>
</template>

<style scoped>
.editor-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  position: relative;
}

.editor-chapters {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
}

.chapter-block {
  border-bottom: 1px solid #eee;
}

.chapter-header {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 10px 12px;
  border: none;
  background: #fafafa;
  cursor: pointer;
  font-size: 13px;
  text-align: left;
  transition: background 0.15s;
}
.chapter-header:hover {
  background: #f0f0f0;
}
.chapter-block.expanded .chapter-header {
  background: #e8f0fe;
}

.chapter-expand-icon {
  flex-shrink: 0;
  width: 14px;
  color: #888;
  text-align: center;
}

.chapter-title {
  font-weight: 600;
  color: #333;
  flex-shrink: 0;
}

.chapter-subtitle {
  flex: 1;
  color: #999;
  font-size: 11px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chapter-char-count {
  flex-shrink: 0;
  color: #1a73e8;
  font-size: 11px;
  font-weight: 600;
}

.chapter-auto-tag {
  flex-shrink: 0;
  color: #999;
  font-size: 10px;
  background: #eee;
  padding: 1px 6px;
  border-radius: 3px;
}

.chapter-body {
  padding: 8px 12px 12px;
  background: #fff;
}

.editor-status {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 4px 12px;
  border-top: 1px solid #eee;
  background: #fafafa;
  flex-shrink: 0;
}
.status-stats {
  font-size: 11px;
  color: #999;
}
.status-clear {
  border: none;
  background: none;
  color: #d32f2f;
  font-size: 11px;
  cursor: pointer;
}
.status-clear:hover {
  text-decoration: underline;
}
</style>
