import type { ChapterDef } from '@/types/editor'

export const CHAPTERS: ChapterDef[] = [
  {
    id: 'abstractZh',
    title: '中文摘要',
    subtitle: '中文摘要 + 关键词（3-5 个）',
    defaultExpanded: false,
  },
  {
    id: 'abstractEn',
    title: '英文摘要',
    subtitle: 'English Abstract + Keywords',
    defaultExpanded: false,
  },
  {
    id: 'toc',
    title: '目录',
    subtitle: '自动从正文标题生成',
    defaultExpanded: false,
    isAutoGenerated: true,
  },
  {
    id: 'body',
    title: '正文',
    subtitle: '标题层级、图表、公式',
    defaultExpanded: true,
  },
  {
    id: 'references',
    title: '参考文献',
    subtitle: 'GB/T 7714 格式文献列表（≥15 篇）',
    defaultExpanded: false,
  },
  {
    id: 'acknowledgement',
    title: '致谢',
    subtitle: '致谢内容（限 1 页内）',
    defaultExpanded: false,
  },
  {
    id: 'appendix',
    title: '附录',
    subtitle: '附录内容（可选）',
    defaultExpanded: false,
  },
]
