/** documentStore.sections 可编辑的文本章节键 */
export type SectionKey = 'abstractZh' | 'abstractEn' | 'body' | 'acknowledgement' | 'appendix'

/** 编辑器手风琴面板的章节元数据 */
export interface ChapterDef {
  id: string
  title: string
  subtitle: string
  defaultExpanded: boolean
  /** 自动生成内容（目录），不可用户编辑 */
  isAutoGenerated?: boolean
}
